version: '3.8'

services:
    api:
        build:
            context: .
            dockerfile: build/Dockerfile
        command: "gunicorn --timeout 30 --bind 0.0.0.0:8000 --worker-class gevent --worker-connections 4096 --workers 4 'app.app:create_app()' --reload"
        ports:
            - "8000:8000"
        environment:
            DATABASE_URL: postgresql://user:password@db:5432/mydatabase
            FLASK_ENV: dev
            FLASK_APP: "app.app:create_app"
        depends_on:
            - db
        volumes:
            - .:/app
    db:
        image: postgres:13
        command: postgres -c 'max_connections=4096'
        environment:
            POSTGRES_DB: mydatabase
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
        volumes:
            - postgres_data:/var/lib/postgresql/data
    tests:
        image: python:3.13.5-bookworm
        command: tail -f /dev/null
        volumes:
            - .:/app
    ui:
        image: nginx:alpine
        ports:
          - "8001:80"
        depends_on:
            - api
        volumes:
          - ./static:/usr/share/nginx/html:ro

volumes:
    postgres_data: